import { formatDateTimeTo12Hour } from './time'

function escapePdfText(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

function pad(value) {
  return String(Math.round(value * 100) / 100)
}

function textCommand(x, y, size, text, font = 'F1') {
  return `BT /${font} ${size} Tf 1 0 0 1 ${pad(x)} ${pad(y)} Tm (${escapePdfText(text)}) Tj ET`
}

function rectCommand(x, y, width, height, stroke = true, fill = false) {
  const mode = fill && stroke ? 'B' : fill ? 'f' : 'S'
  return `${pad(x)} ${pad(y)} ${pad(width)} ${pad(height)} re ${mode}`
}

function lineCommand(x1, y1, x2, y2) {
  return `${pad(x1)} ${pad(y1)} m ${pad(x2)} ${pad(y2)} l S`
}

function colorFill(r, g, b) {
  return `${r} ${g} ${b} rg`
}

function colorStroke(r, g, b) {
  return `${r} ${g} ${b} RG`
}

export function downloadPaymentSlipPdf(ticket) {
  if (!ticket) return

  const bookedAt = formatDateTimeTo12Hour(ticket.bookedAt || new Date())
  const showtime = formatDateTimeTo12Hour(ticket.show?.startsAt)
  const seatList = (ticket.seats || []).map((seat) => seat.seatCode).join(', ') || 'N/A'
  const paymentMethod = String(ticket.payment?.method || 'online').toUpperCase()
  const receiptNumber = ticket.payment?.receiptNumber || `MOVIX-${ticket.bookingId}`
  const paymentId = ticket.payment?.paymentId || 'Pending'
  const orderId = ticket.payment?.orderId || 'Pending'
  const customerEmail = ticket.payment?.customerEmail || 'Not available'
  const paymentStatus = String(ticket.payment?.status || 'captured').toUpperCase()

  const commands = [
    '1 w',
    colorStroke(0.18, 0.14, 0.34),
    rectCommand(28, 28, 539, 786),
    colorFill(0.14, 0.1, 0.28),
    rectCommand(28, 734, 539, 80, false, true),
    colorFill(1, 0.97, 0.92),
    textCommand(48, 776, 24, 'MOVIX PAYMENT SLIP', 'F2'),
    textCommand(48, 756, 10, 'Razorpay-confirmed movie booking receipt'),
    colorFill(0.96, 0.97, 1),
    colorStroke(0.86, 0.88, 0.95),
    rectCommand(48, 632, 499, 84, true, true),
    colorFill(0.1, 0.09, 0.16),
    textCommand(64, 688, 16, ticket.show?.movieTitle || 'Movie Booking', 'F2'),
    textCommand(64, 666, 10, `${ticket.show?.theaterName || 'Theater'} | ${ticket.show?.hallName || 'Hall'}`),
    textCommand(64, 646, 10, `Showtime: ${showtime}`),
    colorFill(1, 1, 1),
    rectCommand(48, 474, 239, 132, true, true),
    rectCommand(308, 474, 239, 132, true, true),
    rectCommand(48, 288, 499, 162, true, true),
    colorFill(0.24, 0.2, 0.42),
    textCommand(64, 582, 11, 'CUSTOMER', 'F2'),
    textCommand(324, 582, 11, 'PAYMENT', 'F2'),
    textCommand(64, 426, 11, 'REFERENCE DETAILS', 'F2'),
    colorFill(0.1, 0.09, 0.16),
    textCommand(64, 556, 10, `Email: ${customerEmail}`),
    textCommand(64, 536, 10, `Seats: ${seatList}`),
    textCommand(64, 516, 10, `Booked At: ${bookedAt}`),
    textCommand(324, 556, 10, `Amount Paid: INR ${Number(ticket.totalAmount || 0)}`),
    textCommand(324, 536, 10, `Method: ${paymentMethod}`),
    textCommand(324, 516, 10, `Status: ${paymentStatus}`),
    textCommand(64, 400, 10, `Receipt Number: ${receiptNumber}`),
    textCommand(64, 378, 10, `Razorpay Payment ID: ${paymentId}`),
    textCommand(64, 356, 10, `Razorpay Order ID: ${orderId}`),
    textCommand(64, 334, 10, `Booking ID: ${ticket.bookingId}`),
    textCommand(64, 312, 10, 'This slip can be used as payment proof for the booking above.'),
    colorStroke(0.86, 0.88, 0.95),
    lineCommand(48, 248, 547, 248),
    colorFill(0.42, 0.39, 0.52),
    textCommand(48, 228, 9, 'Generated by Movix from verified Razorpay payment details.'),
  ]

  const stream = commands.join('\n')
  const objects = []
  const addObject = (body) => {
    objects.push(body)
    return objects.length
  }

  addObject('<< /Type /Catalog /Pages 2 0 R >>')
  addObject('<< /Type /Pages /Kids [3 0 R] /Count 1 >>')
  addObject(
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>'
  )
  addObject(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)
  addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
  addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>')

  let pdf = '%PDF-1.4\n'
  const offsets = [0]

  objects.forEach((body, index) => {
    offsets.push(pdf.length)
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`
  })

  const xrefStart = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`

  const blob = new Blob([pdf], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `movix-payment-slip-${ticket.bookingId}.pdf`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}
